services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379

  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - REDIS_ADDR=redis:6379
    restart: always